### ISSUE TITLE
Player Help Guide menu has incorrect keys

### ISSUE THREAD

**Issue by hord-brayden** [Sirrine-Jonathan/Afghan_Trail#6]
In the help menu when traveling in the wilderness, the help menu has the wrong keys written out

Game Menu
C - Continue
M - Map
S - Log Player Stats
I - Log Player Inventory
G - Guide
E - Exit without saving
>>>
G
GAME MENU GUIDE

	Pressing W

Continue will move your character
to thier next adventure event

	Pressing A

Map will show the map of the
afghan trail and your character's position

	Pressing S

Player Stats will show your
character's stats
	Pressing D

Player inventory will be shown
	Pressing Q

Displays this game guide
	Pressing E

Exits the game without saving
Saving can only be done in towns

Game Menu
C - Continue
M - Map
S - Log Player Stats
I - Log Player Inventory
G - Guide
E - Exit without saving

**Comment by Sirrine-Jonathan** [comment]
changed keys in guide to take from keys array instead of being hard-coded.
